[package]
name = "parflow-live-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
colored = "2.0"
crossterm = "0.27"
tui = "0.19"
