edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"
imports_granularity = "Module"
reorder_imports = true
reorder_modules = true
format_strings = true
comment_width = 100
wrap_comments = true
normalize_comments = false
