[package]
name = "parflow-grpc"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
parflow-core = { path = "../parflow-core" }
tonic = "0.9"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "full"] }
prost = "0.11.9"

[build-dependencies]
tonic-build = "0.9"
