[package]
name = "parflow-rest"
version = "0.1.0"
edition = "2021"

[dependencies]
parflow-core = { path = "../parflow-core" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
axum = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
