[package]
name = "parflow-mirror"
version = "0.1.0"
edition = "2021"

[dependencies]
semantic-compiler = { path = "../semantic-compiler" }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
colored = "2.0"
