name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install protoc for gRPC
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Run tests
        run: cargo test --workspace

  build:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install protoc for gRPC
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Build project
        run: cargo build --workspace --release

  wasm:
    name: Build WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Build WASM Crate
        run: cargo build -p parflow-wasm --target wasm32-unknown-unknown --release
