name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Run workspace tests
        run: cargo test --workspace

      - name: Build all crates
        run: cargo build --workspace --release

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Build WASM crate
        run: cargo build -p parflow-wasm --target wasm32-unknown-unknown --release

      - name: Build C library
        run: cargo build -p parflow-c --release

